### ISSUE TITLE
showStep event stepDirection is always "backward"

### ISSUE THREAD

**Issue by RocketSquirrel** [techlab/jquery-smartwizard#91] opened 2020-06-22 18:37 UTC
**Describe the bug**
showStep event handler parameter stepDirection is always "backward" even when navigating forward.

**To Reproduce**
1. Click next
2. log stepDirection
3. Observe that the value is always "backward"

**Expected behavior**
In v4 when navigating forward the stepDirection value was "forward"

**Desktop (please complete the following information):**
Tested on Chrome Version 83.0.4103.106 (Official Build) (64-bit) and Firefox 77.0.1 (64-bit)

**Comment by techlab** [comment] 2020-07-10 16:07
The issue is fixed on [v5.1.1](https://github.com/techlab/jquery-smartwizard/releases/tag/v5.1.1). 
Thanks for reporting the issue @RocketSquirrel

**Closed by techlab** 2020-07-10 16:07 UTC
Labels: bug
