### ISSUE TITLE
Collapse in theme arrows is possible?

### ISSUE THREAD

**Issue by pr0mming** [techlab/jquery-smartwizard#75] opened 2019-04-24 15:27 UTC
Hi all,

I am using the application with the theme "arrows", but I have seen a problem and if I add several menus (more than six and varying the size of the text) and the text of the menus is too long the menu is damaged as shown here when the screen adapts:

![arr](https://user-images.githubusercontent.com/20020612/56671443-46b7ba80-667a-11e9-891d-2f375f8bb437.png)

Actually I'm not very knowledgeable about Bootstrap or CSS, but is it possible that the menu is collapsing? That is, if I am in the active tab, the full text should be shown: "Step Full Text 0000001" but the inactive tabs should be attached to the size of the menu, then the text should not be shown complete but as "Step Fu", or "Step", etc. without damaging the shape of the eyelashes.

I'm looking for examples that have the functionality I'm looking for but in several examples I've seen the menu text is vertical, which is not what I'm looking for:

https://www.codeply.com/go/nBRcoEWHcN/bootstrap-responsive-horizontal-accordion-panels

I am not sure if I have explained my problem well but is it possible to implement a behavior of this type?

**Comment by techlab** [comment] 2020-06-27 14:56
Hi @pr0mming The problem is now fixed on the latest version (jQuery Smart Wizard v5). Thank you for reporting the issue with details.

**Closed by techlab** 2020-06-27 14:56 UTC
