### ISSUE TITLE
unDoneOnBackNavigation not removing done

### ISSUE THREAD

**Issue by justinkruit** [techlab/jquery-smartwizard#146] opened 2022-08-02 12:31 UTC
**Describe the bug**
I've created a wizard, and adding `unDoneOnBackNavigation` in the `anchor` settings doesn't remove the `done` class from items after the navigation item when I go back.

**To Reproduce**
1. Create a wizard
2. Add `anchor: { unDoneOnBackNavigation: true, }` as setting
3. See it not working

**Expected behavior**
I expect the `done` class to be removed when I go back one tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/1642830/182374707-08a903f6-6f46-48a1-897d-ef6e365f22cb.png)
I went from 1, to 2, and then back to 1.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 103.0.5060.134

**Comment by XjSv** [comment] 2022-08-04 03:25
Same here, I'm pretty much using the default settings.

**Comment by XjSv** [comment] 2022-08-04 04:03
It looks like there is already a fix for it in the v6.x branch. The bug was introduced in [v6.0.3](https://github.com/techlab/jquery-smartwizard/releases/tag/v6.0.3) in this commit https://github.com/techlab/jquery-smartwizard/commit/e76b32b9d9d98b4d259ae607419dc523048d90ac. When using the v6.x branch it works as intended.

**Comment by techlab** [comment] 2022-08-07 08:09
@justinkruit  The issue is fixed on [v6.0.5](https://github.com/techlab/jquery-smartwizard/releases/tag/v6.0.5)
Thank you for reporting it. 
FYI @XjSv

**Closed by techlab** 2022-08-07 08:09 UTC
Labels: bug
